# Exercice 2
Construire les opérations matricielles suivantes :
1. Calcul d’un produit Matrice × Vecteur.
- Réserver 9 cases (3 lignes, 3 colonnes) pour définir une matrice M.
- À côté, réserver 3 cases (en colonne) pour définir un vecteur V.
- Construire le vecteur résultat dans 3 cases situées à côté (en colonne) M × V.

In [16]:
# Définition de la matrice M (3x3)
#exercice 2:
 
#partie 1
 
import numpy as np
 
 
M=np.array([
    [3,6,9],
    [2,4,6],
    [10,15,7]
])
 
V=np.array([1,2,3])
 
 
#calculer le produit
print(M*V)
 
np.dot(M,V)

[[ 3 12 27]
 [ 2  8 18]
 [10 30 21]]


array([42, 28, 61])

In [12]:
import numpy as np
M = np.array([
    [3, 6, 9],
    [2, 4, 6],
    [10, 15, 7]
])

det_m = np.linalg.det(M)
print("Déterminant de M :", det_m)

Déterminant de M : -3.996802888650553e-14
